__all__ = ['_CUDA_LAYER_NORM_OPT', '_CUDA_AMP_OPT', '_CPU_IPEX_OPT', '_CPU_FLUSH_DENORM_OPT', '_CPU_AMP_OPT', '_SCORE_TABLE_TIMESTAMP', '_SCORE_TABLE_DISPALY_TOP', '_SCORE_TABLE_DISPALY_AVG', '_TRITON_LAYER_NORM_OPT', '_TRITON_GLU_OPT', '_CUDA_GLU_OPT', '_TRITON_DPA_OPT', '_CUDA_LAYER_NORM_OPT']

# GPU
_CUDA_AMP_OPT = True

_TRITON_LAYER_NORM_OPT = False
_CUDA_LAYER_NORM_OPT = True

_TRITON_GLU_OPT = True
_CUDA_GLU_OPT = False

_TRITON_DPA_OPT = True
# CPU
_CPU_IPEX_OPT = False
_CPU_FLUSH_DENORM_OPT = False
_CPU_AMP_OPT = False

# DEBUG
_SCORE_TABLE_TIMESTAMP = False
_SCORE_TABLE_DISPALY_TOP = True
_SCORE_TABLE_DISPALY_AVG = True

#检测互斥
assert not (_TRITON_GLU_OPT and _CUDA_GLU_OPT)
assert not (_TRITON_LAYER_NORM_OPT and _CUDA_LAYER_NORM_OPT)