__all__ = ['_CUDA_LAYER_NORM_OPT', '_CUDA_AMP_OPT', '_CPU_IPEX_OPT', '_CPU_FLUSH_DENORM_OPT', '_CPU_AMP_OPT', '_SCORE_TABLE_TIMESTAMP', '_SCORE_TABLE_DISPALY_TOP', '_SCORE_TABLE_DISPALY_AVG']

# GPU
_CUDA_LAYER_NORM_OPT = False
_CUDA_AMP_OPT = True

# CPU
_CPU_IPEX_OPT = True
_CPU_FLUSH_DENORM_OPT = True
_CPU_AMP_OPT = True

# DEBUG
_SCORE_TABLE_TIMESTAMP = False
_SCORE_TABLE_DISPALY_TOP = True
_SCORE_TABLE_DISPALY_AVG = True